from typing import Any, TYPE_CHECKING
import uuid
from sqlalchemy import ForeignKey, String
from sqlalchemy.dialects.postgresql import JSONB, UUID
from sqlalchemy.orm import Mapped, mapped_column, relationship
from app.db.base_class import Base

if TYPE_CHECKING:
    from .consultation import Consultation


class MedicalNote(Base):
    """
    SQLAlchemy model representing clinical documents or summaries generated by the scribe platform.
    """
    __tablename__ = "medical_notes"

    consultation_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True),
        ForeignKey("consultations.id", ondelete="CASCADE"),
        nullable=False
    )
    note_type: Mapped[str] = mapped_column(
        String(50),
        default="soap",
        nullable=False
    )
    content: Mapped[Any] = mapped_column(JSONB, nullable=False)

    # Relationships
    consultation: Mapped["Consultation"] = relationship("Consultation", back_populates="medical_notes")
